- ignore:
    name: "Eta reduce"
- ignore:
    name: "Use list comprehension"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use tuple-section"
- ignore:
    name: "Use fmap"
- ignore:
    name: "Use const"
