resolver: lts-23.19
packages:
# Code generator
- schema-dot-org-generator

# Generated code
- schema-dot-org

# Companions
- schema-dot-org-jsonld



system-ghc: true
nix:
  enable: false
with-hpack: hpack
