name: schema-dot-org-jsonld
version: 0.0.0.0
github: "NorfairKing/schema-dot-org"
author: "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - scalpel
  - schema-dot-org
  - tagsoup
  - text
