name: schema-dot-org-jsonld
version: 0.0.0.0
github: "NorfairKing/schema-dot-org"
author: "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - schema-dot-org
  - tagsoup
  - text
  - vector

tests:
  schema-dot-org-jsonld-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aeson
    - bytestring
    - schema-dot-org-jsonld
    - sydtest
    - sydtest-aeson
