name:                schema-dot-org-generator
version:             0.0.0.0
github:              "NorfairKing/schema-dot-org"
author:              "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - ghc-paths
    - ghc
    - ghc-source-gen

executables:
  schema-dot-org-generator:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - schema-dot-org-generator
